= Advanced Route Rules
include::_attributes.adoc[]

[#canarydeploymentuseragent]
== 접속 웹브라우저에 따른 스마트한 라우팅 (Canary Deployment)

What is your user-agent?

https://www.whoishostingthis.com/tools/user-agent/[https://www.whoishostingthis.com/tools/user-agent/]

Note: the "user-agent" header is added to OpenTracing baggage in the Customer service. From
there it is automatically propagated to all downstream services. To enable automatic
baggage propagation all intermediate services have to be instrumented with OpenTracing.
The baggage header for user agent has following form `baggage-user-agent: <value>`.

[#alltorecommendationv1]
=== 먼저 모든 트래픽을 v1 로 전송합니다

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml 
istioctl create -f istiofiles/virtual-service-recommendation-v1.yml
----

[#safaritov2]
=== 사파리 유저만 v2로 라우팅

[source,bash]
----
istioctl replace -f istiofiles/virtual-service-safari-recommendation-v2.yml

istioctl get virtualservice -n tutorial
----

그런후에 Safari 브라우저로 접속합니다.(혹은 Firefox 브라우저용 설정으로 디플로이 한후, 예제를 테스트 합니다.



혹은,  curl -A 커맨드를 통하여  user-agent 문자열을 전달할 수 있습니다. 

[source,bash]
----
curl -A Safari <service url>
curl -A Firefox <service url>
----


[#mirroringtraffic]
== 트래픽 미러링 (Dark Launch or Shaddow deploy)

새도우 배포를 테스트하기 위해서는 recommendation 버전이 2개 이상있어야 합니다. 실제 트래픽의 결과는 모두 v1것을 유저로 보내면서 v2

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl create -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n tutorial

curl <service url>
----

recommendation-v2 의 로그 확인하기

[source,bash]
----
kubectl logs -f `oc get pods|grep recommendation-v2|awk '{ print $1 }'` -c recommendation
----


[#accesscontrol]
== Access Control

IMPORTANT: The Access Control rules take some time to be applied and reflected. Be patient here!

[#whitelist]
=== Whitelist

We'll create a whitelist on the preference service to only allow requests from the recommendation service, which will make the preference service invisible to the customer service. Requests from the customer service to the preference service will return a 404 Not Found HTTP error code.

[source,bash]
----
istioctl create -f istiofiles/acl-whitelist.yml -n tutorial
----

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => 404 NOT_FOUND:preferencewhitelist.listchecker.tutorial:customer is not whitelisted
----

==== Clean up

[source,bash]
----
istioctl delete -f istiofiles/acl-whitelist.yml -n tutorial
----

[#blacklist]
=== Blacklist

We'll create a blacklist making the customer service blacklist to the preference service. Requests from the customer service to the preference service will return a 403 Forbidden HTTP error code.

[source,bash]
----
istioctl create -f istiofiles/acl-blacklist.yml -n tutorial
----

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
customer => 403 PERMISSION_DENIED:denycustomerhandler.denier.tutorial:Not allowed
----

==== Clean up

[source,bash]
----
istioctl delete -f istiofiles/acl-blacklist.yml -n tutorial
----

[#loadbalancer]
== Load Balancer

By default, you will see "round-robin" style load-balancing, but you can change it up, with the RANDOM option being fairly visible to the naked eye.

Add another v2 pod to the mix

[source,bash]
----
oc scale deployment recommendation-v2 --replicas=2 -n tutorial
or
kubectl scale deployment recommendation-v2 --replicas=2 -n tutorial
----

Wait a bit (oc get pods -w to watch)
and curl the customer endpoint many times

[source,bash]
----
curl customer-tutorial.$(minishift ip).nip.io
----

Add a 3rd v2 pod to the mix

[source,bash]
----
$ oc scale deployment recommendation-v2 --replicas=3 -n tutorial
$ oc get pods -n tutorial

or 

$ kubectl scale deployment recommendation-v2 --replicas=3 -n tutorial
$ kubectl get pods -n tutorial


NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f          2/2       Running   0          1h
recommendation-v1-3719512284-bn42p   2/2       Running   0          59m
recommendation-v2-2815683430-97nnf   2/2       Running   0          43m
recommendation-v2-2815683430-d49n6   2/2       Running   0          51m
recommendation-v2-2815683430-tptf2   2/2       Running   0          33m
----

Wait for those 2/2 (two containers in each pod) and then poll the customer endpoint:

[source, bash]
----
./scripts/run.sh
----

The results should follow a fairly normal round-robin distribution pattern

[source,bash]
----
customer => preference => recommendation v1 from '99634814-d2z2t': 1145
customer => preference => recommendation v2 from '2819441432-525lh': 1
customer => preference => recommendation v2 from '2819441432-rg45q': 2
customer => preference => recommendation v2 from '2819441432-bs5ck': 181
customer => preference => recommendation v1 from '99634814-d2z2t': 1146
customer => preference => recommendation v2 from '2819441432-rg45q': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 4
customer => preference => recommendation v2 from '2819441432-bs5ck': 182
----

Now, add the Random LB DestinationPolicy

[source,bash]
----
istioctl create -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n tutorial
----

And you should see a different pattern of which pod is being selected

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-rg45q': 10
customer => preference => recommendation v2 from '2819441432-525lh': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 11
customer => preference => recommendation v1 from '99634814-d2z2t': 1153
customer => preference => recommendation v1 from '99634814-d2z2t': 1154
customer => preference => recommendation v1 from '99634814-d2z2t': 1155
customer => preference => recommendation v2 from '2819441432-rg45q': 12
customer => preference => recommendation v2 from '2819441432-525lh': 4
customer => preference => recommendation v2 from '2819441432-525lh': 5
customer => preference => recommendation v2 from '2819441432-rg45q': 13
customer => preference => recommendation v2 from '2819441432-rg45q': 14
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n tutorial

oc scale deployment recommendation-v2 --replicas=1 -n tutorial
or
kubectl scale deployment recommendation-v2 --replicas=1 -n tutorial
----

[#ratelimiting]
== Rate Limiting

IMPORTANT: The Rate Limiting rules take some time to be applied and reflected. Be patient here!

Here we will limit the number of concurrent requests into recommendation v2

Now apply the rate limit handler

[source,bash]
----
istioctl create -f istiofiles/recommendation_rate_limit_handler.yml
----

Now setup the requestcount quota

[source,bash]
----
istioctl create -f istiofiles/rate_limit_rule.yml
----

Throw some requests at customer:

[source, bash]
----
./scripts/run.sh
----

You should see some 429 errors:

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-f4ls5': 108
customer => preference => recommendation v1 from '99634814-d2z2t': 1932
customer => preference => recommendation v2 from '2819441432-f4ls5': 109
customer => preference => recommendation v1 from '99634814-d2z2t': 1933
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1934
customer => preference => recommendation v2 from '2819441432-f4ls5': 110
customer => preference => recommendation v1 from '99634814-d2z2t': 1935
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1936
customer => preference => recommendation v2 from '2819441432-f4ls5': 111
customer => preference => recommendation v1 from '99634814-d2z2t': 1937
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1938
customer => preference => recommendation v2 from '2819441432-f4ls5': 112
----

Clean up

[source,bash]
----
istioctl delete -f istiofiles/rate_limit_rule.yml

istioctl delete -f istiofiles/recommendation_rate_limit_handler.yml
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----
